a2lix_translation_form:
  locale_provider: default
  locales: ['ru', 'en']
  default_locale: '%app.default_locale%'
  required_locales: [ru]
  templating: '@A2lixTranslationForm/bootstrap_5_layout.html.twig'