# config/packages/ckfinder.yml

ckfinder:
  connector:
    licenseName: LICENSE-NAME
    licenseKey: LICENSE-KEY
    authenticationClass: App\Security\CKFinderAuthentication
    backends:
      - name: default
        baseUrl: '/storage/uploads/'
        root: '%kernel.project_dir%/public/storage/uploads'
    resourceTypes:
      files:
        name: 'Файлы'
        backend: default
        directory: 'files'
      images:
        name: 'Картинки'
        backend: default
        directory: 'images'