fos_ck_editor:
    base_path: '../bundles/fosckeditor'
    js_path:   '../bundles/fosckeditor/ckeditor.js'
    default_config: eft_config
    configs:
        eft_config:
            mode: 'modal'
            extraPlugins: [ 'filebrowser' ]
            extraAllowedContent : "div[*]"
            allowedContent: true
            image_previewTextSince: ''
            removeDialogTabs: 'image:advanced, link:advanced'
            filebrowserBrowseUrl: '/bundles/cksourceckfinder/ckfinder/ckfinder.html'
#            filebrowserImageBrowseUrl: '/ckfinder/connector?type=Images'
#            filebrowserUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Files'
#            filebrowserImageUploadUrl: '/ckfinder/connector?command=QuickUpload&type=Images'
            toolbar: [
                [ 'Source' ]
                [ 'Undo', 'Redo' ],
                [ 'Styles', 'Format' ],
                [ 'Bold', 'Italic', 'Strike', '-', 'RemoveFormat' ],
                [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ],
                [ 'Link', 'Unlink' ],
                [ 'Image', 'Table' ],
                [ 'Maximize' ],
                [ 'Scayt' ]
            ]
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
