# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    cache: images
    data_loader: default
    default_image: null
    twig:
        mode: lazy
    default_filter_set_settings:
        quality: 100
        jpeg_quality: ~
        png_compression_level: ~
        png_compression_filter: ~
        animated: false
        format: ~
        cache: ~
        data_loader: ~
        default_image: null
        filters: [ ]
        post_processors: [ ]

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: "storage/cache"

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    filter_sets:
        cache: ~
        34x34:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 34, 34 ], position: center, mode: inset }
        100x100:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 100, 100 ], position: center, mode: inset }
        120x120:
            cache: default
            quality: 100
            filters:
                fixed:
                    width: 120
                    height: 120
#                thumbnail: { size: [ 100, 100 ], position: center, mode: inset }
        180x134:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 180, 134 ], position: center, mode: inset }
        78x78:
            cache: default
            quality: 100
            filters:
                fixed:
                    width: 78
                    height: 78
#                thumbnail: { size: [ 158, 158 ], position: center, mode: inset }
        158x158:
            cache: default
            quality: 100
            filters:
                fixed:
                    width: 158
                    height: 158
#               thumbnail: { size: [ 158, 158 ], position: center, mode: inset }
        110x90:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 110, 90 ], position: center, mode: inset }
        118x118:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 118, 118 ], position: center, mode: inset }
        178x178:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 178, 178 ], position: center, mode: inset }
        180x90:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 180, 90 ], position: center, mode: inset }
        250x148:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 250, 148 ], position: center, mode: inset }
        257x77:
            cache: default
            quality: 100
            filters:
                fixed:
                    width: 257
                    height: 77
#                thumbnail: { size: [ 257, 77 ], position: center, mode: inset }
        350x150:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 350, 150 ], position: center, mode: inset }
        360x210:
            cache: default
            quality: 100
            filters:
                thumbnail: { size: [ 360, 210 ], position: center, mode: inset }