# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    cache: images
    data_loader: default
    default_image: null
    twig:
        mode: lazy
    default_filter_set_settings:
        quality: 100
        jpeg_quality: ~
        png_compression_level: ~
        png_compression_filter: ~
        animated: false
        format: ~
        cache: ~
        data_loader: ~
        default_image: null
        filters: [ ]
        post_processors: [ ]

    resolvers:
        images:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: "storage/cache"

    loaders:
        images:
            filesystem:
                data_root: '%kernel.project_dir%/public/storage'

    filter_sets:
        cache: ~
        100x100:
            cache: images
            quality: 100
            filters:
                thumbnail: { size: [ 100, 100 ], position: center, mode: inset }
        180x134:
            cache: images
            quality: 100
            filters:
                thumbnail: { size: [ 180, 134 ], position: center, mode: inset }