framework:
    default_locale: '%app.default_locale%'
    enable_locales: ['ru', 'en']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallback: '%app.default_locale%'
