vich_uploader:
    db_driver: orm

    mappings:
        locations:
            uri_prefix: '%app.locations.images.uri%'
            upload_destination: '%app.locations.images.path%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        traders:
            uri_prefix: '%app.traders.images.uri%'
            upload_destination: '%app.traders.images.path%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        articles:
            uri_prefix: '%app.articles.images.uri%'
            upload_destination: '%app.articles.images.path%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        quests:
            uri_prefix: '%app.quests.images.uri%'
            upload_destination: '%app.quests.images.path%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        items:
            uri_prefix: '%app.items.images.uri%'
            upload_destination: '%app.items.images.path%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true