# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_dir: '%env(APP_DIR)%'

    doctrine_behaviors_translatable_fetch_mode: 'LAZY'
    doctrine_behaviors_translation_fetch_mode: 'LAZY'
    doctrine_behaviors_timestampable_date_field_type: "datetime"

    # Locales
    app.default_locale: 'ru'
    app.additional_locales: 'en'

    app.storage.path: '%kernel.project_dir%/public/storage/'
    app.storage.uri: '%app_dir%/storage/'
    app.storage.cache_uri: '%app_dir%/storage/cache/'

    # Traders image config
    app.traders.images.path: '%app.storage.path%images/traders'
    app.traders.images.uri: '%app.storage.uri%images/traders'

    # Maps image config
    app.maps.images.path: '%app.storage.path%images/locations'
    app.maps.images.uri: '%app.storage.uri%images/locations'

    # Locations image config
    app.locations.images.path: '%app.storage.path%images/locations'
    app.locations.images.uri: '%app.storage.uri%images/locations'

    # Locations image config
    app.articles.images.path: '%app.storage.path%images/articles'
    app.articles.images.uri: '%app.storage.uri%images/articles'

    # Bosses image config
    app.enemies.images.path: '%app.storage.path%images/enemies'
    app.enemies.images.uri: '%app.storage.uri%images/enemies'

    # Quests image config
    app.quests.images.path: '%app.storage.path%images/quests'
    app.quests.images.uri: '%app.storage.uri%images/quests'

    # Items image config
    app.items.images.path: '%app.storage.path%images/items'
    app.items.images.uri: '%app.storage.uri%images/items'

    # Quests items image config
    app.quests_items.images.path: '%app.storage.path%images/quests-items'
    app.quests_items.images.uri: '%app.storage.uri%images/quests-items'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.eventListeners.localeParamListener:
        class: App\EventListener\LocaleParamListener
        arguments: ["@router", "%app.default_locale%", "%app.additional_locales%"]
        tags:
            - { name: kernel.event_subscriber }
